name: demo github actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/new
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/new
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
      - name: ssh connect and clone
        run: |
          ssh "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" << EOF
          echo ----- take clone in remote server -----
          mkdir hello
          exit
          EOF
      - name: cleanup
        run: | 
          rm -rf ~/.ssh
